name: "Build"

on:
  push:
    branches:
      -  master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build
        run: |
          cargo build